[http]

  [http.routers]
    [http.routers.routerTest]
      service = "k3s"
      rule = "Host(`192.168.123.101`)"

  [http.services]
    [http.services.k3s]
      [http.services.k3s.loadBalancer]
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://192.168.123.100:6443"
